ignore:
  - config/*
  - elosys-rust-nodejs/*
comment: false
github_checks:
  annotations: false
coverage:
  fixes:
    - "/home/runner/work/elosys/elosys/::/"
  status:
    patch:
      default:
        target: 10%
        threshold: 0%
    project:
      default:
        target: 10%
      elosys-rust:
        target: 10%
        flags:
          - elosys-rust
      elosys-cli:
        target: 10%
        flags:
          - elosys-cli
      elosys:
        target: 10%
        flags:
          - elosys
flags:
  elosys-rust:
    paths:
      - elosys-rust
    carryforward: true
  elosys:
    paths:
      - elosys
    carryforward: true
