name: Push new version number to API
on:
  workflow_dispatch:
    inputs:
      push_mainnet:
        description: "mainnet"
        type: boolean
        default: false
      push_testnet:
        description: "testnet"
        type: boolean
        default: false

jobs:
  Push:
    name: Push Version to API
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Push version string to mainnet API
        if: ${{ inputs.push_mainnet }}
        run: ./elosys-cli/scripts/push-version.sh
        env:
          ELOSYS_API_KEY: ${{ secrets.ELOSYS_API_KEY }}
          ELOSYS_API_URL: ${{ secrets.ELOSYS_API_URL }}

      - name: Push version string to testnet API
        if: ${{ inputs.push_testnet }}
        run: ./elosys-cli/scripts/push-version.sh
        env:
          ELOSYS_API_KEY: ${{ secrets.ELOSYS_API_KEY_TESTNET }}
          ELOSYS_API_KEY: ${{ secrets.ELOSYS_API_KEY_TESTNET }}
