on:
  pull_request:
    paths:
      - "benchmarks/**"
      - "elosys-mpc/**"
      - "elosys-phase2/**"
      - "elosys-rust/**"
      - "elosys-rust-nodejs/**"
      - "elosys-zkp/**"
      - "rust-toolchain"
      - ".github/workflows/rust*"
      - ".cargo/**"
      - "Cargo*"
  push:
    branches:
      - master
    paths:
      - "benchmarks/**"
      - "elosys-mpc/**"
      - "elosys-phase2/**"
      - "elosys-rust/**"
      - "elosys-rust-nodejs/**"
      - "elosys-zkp/**"
      - "rust-toolchain"
      - ".github/workflows/rust*"
      - ".cargo/**"
      - "Cargo*"

name: Rust CI

jobs:
  rust_lint:
    name: Lint Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          shared-key: base

      - name: Install Cargo tools
        run: |
          rustup component add rustfmt clippy

      - name: Check that cargo lockfile is up to date
        run: |
          cargo check --locked --all-targets

      # Note: elosys-zkp is does not need this due to different licensing
      - name: Check for license headers for elosys-rust
        run: ./ci/lintHeaders.sh ./elosys-rust/src *.rs

      - name: Check for license headers for elosys-rust-nodejs
        run: ./ci/lintHeaders.sh ./elosys-rust-nodejs/src *.rs

      - name: "`cargo fmt` check on elosys-rust"
        run: |
          cargo fmt --all -- --check

      - name: "Clippy check on elosys-rust"
        run: |
          cargo clippy --all-targets -- -D warnings

  elosys_rust:
    name: Test elosys-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: base

      # Run tests to collect code coverage
      - name: Run cargo-tarpaulin on elosys-rust
        run: |
          wget -O tarpaulin.tar.gz https://github.com/xd009642/tarpaulin/releases/download/0.22.0/cargo-tarpaulin-0.22.0-travis.tar.gz
          tar -xzf tarpaulin.tar.gz
          mv cargo-tarpaulin ~/.cargo/bin/
          cargo tarpaulin -p elosys --release --out Xml --avoid-cfg-tarpaulin --skip-clean --timeout 300 -- --test-threads 1

      # Upload code coverage to Codecov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: elosys-rust

  elosys_zkp:
    name: Test elosys-zkp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: zkp

      # Run tests to collect code coverage
      - name: Run cargo-tarpaulin on elosys-zkp
        run: |
          wget -O tarpaulin.tar.gz https://github.com/xd009642/tarpaulin/releases/download/0.22.0/cargo-tarpaulin-0.22.0-travis.tar.gz
          tar -xzf tarpaulin.tar.gz
          mv cargo-tarpaulin ~/.cargo/bin/
          cargo tarpaulin -p elosys_zkp --release --out Xml --avoid-cfg-tarpaulin --skip-clean --timeout 300 -- --test-threads 1

      # Upload code coverage to Codecov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: elosys-zkp
